function createfigure_22(ZData1, YData1, XData1, CData1, xdata2, ydata2, zdata2, CData2)
%CREATEFIGURE(ZData1, YData1, XData1, CData1, xdata2, ydata2, zdata2, CData2)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata
%  XDATA2:  contour x
%  YDATA2:  contour y
%  ZDATA2:  contour z
%  CDATA2:  surface cdata

%  Auto-generated by MATLAB on 09-Feb-2021 20:53:38

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create surface
surface('Parent',subplot1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'AlignVertexCenters','on',...
    'EdgeColor','none',...
    'CData',CData1);

% Create contour
contour(xdata2,ydata2,zdata2,'Parent',subplot1,'LineWidth',3,'LevelList',1);

% Create ylabel
ylabel('$$v_{e\perp}$$','FontSize',20,'Interpreter','latex');

% Create xlabel
xlabel('$$v_{e\|}$$','FontSize',20,'Interpreter','latex');

% Create title
title('$$\Delta VDF_{e} / VDF_{e,0}$$','FontSize',20,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[-1.2 1.2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 2.4]);
box(subplot1,'on');
axis(subplot1,'square');
% Set the remaining axes properties
set(subplot1,'CLim',[0.1 50],'ColorScale','log','Colormap',...
    [1 1 1;1 0.888888888888889 0.888888888888889;1 0.777777777777778 0.777777777777778;1 0.666666666666667 0.666666666666667;1 0.555555555555556 0.555555555555556;1 0.444444444444444 0.444444444444444;1 0.333333333333333 0.333333333333333;1 0.222222222222222 0.222222222222222;1 0.111111111111111 0.111111111111111;1 0 0],...
    'FontSize',18);
% Create colorbar
colorbar(subplot1);

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create surface
surface('Parent',subplot2,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'AlignVertexCenters','on',...
    'EdgeColor','none',...
    'CData',CData2);

% Create contour
[c1,h1] = contour(xdata2,ydata2,zdata2,'Parent',subplot2,'LineWidth',3,...
    'LevelList',1);

% Create ylabel
ylabel('$$v_{e\perp}$$','FontSize',20,'Interpreter','latex');

% Create xlabel
xlabel('$$v_{e\|}$$','FontSize',20,'Interpreter','latex');

% Create title
title('$$-\Delta VDF_{e} / VDF_{e,0}, \ t_{i}=$$45.73$$ \ \Omega_{e}^{-1}$$',...
    'FontSize',20,...
    'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[-1.2 1.2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 2.4]);
box(subplot2,'on');
axis(subplot2,'square');
% Set the remaining axes properties
set(subplot2,'CLim',[0.1 50],'ColorScale','log','Colormap',...
    [1 1 1;0.888888888888889 0.888888888888889 1;0.777777777777778 0.777777777777778 1;0.666666666666667 0.666666666666667 1;0.555555555555556 0.555555555555556 1;0.444444444444444 0.444444444444444 1;0.333333333333333 0.333333333333333 1;0.222222222222222 0.222222222222222 1;0.111111111111111 0.111111111111111 1;0 0 1],...
    'FontSize',18);
% Create colorbar
colorbar(subplot2);

