%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/jeffersson_agudelo/Documents/PSC_here/PSC_This_mac/test_runs_here/my_case_particles/pxyzi.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/18 21:16:36

%% Initialize variables.
filename = '/Users/jeffersson_agudelo/Documents/PSC_here/PSC_This_mac/test_runs_here/my_case_particles/pxyzi.txt';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%10f%11f%11f%11f%11f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
x1 = dataArray{:, 1};
y1 = dataArray{:, 2};
z1 = dataArray{:, 3};
px1 = dataArray{:, 4};
py1 = dataArray{:, 5};
pz1 = dataArray{:, 6};


%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;
%% Clear temporary variables


% play with the data
 pm1=sqrt(px1.*px1 + py1.*py1 + pz1.*pz1);

